### ISSUE TITLE
Hide Date In TimePicker View

### ISSUE THREAD

**Issue by jaletechs** [nathanreyes/v-calendar#1234]
Never thought I'd come across this use case, but recently, I have been interested in hiding the date that appears just above the timepicker. I've checked the attributes possible, and there's none for that.
![Screenshot 2022-12-22 at 8 09 52 am](https://user-images.githubusercontent.com/22795062/209087892-9175683e-2039-4acf-97f0-622edcceefce.png)

**Comment by GrandWin** [comment]
You must set mode="time" to select only time
https://vcalendar.io/datepicker.html#time

**Comment by nkeyy0** [comment]
Probably you cannot achieve this by adding some prop because the date is passing to the child `TimePicker` component. And as you can see in a picture the value is the required prop for the `TimePicker` component. You could try to hide this date field via CSS (second picture)
![image](https://user-images.githubusercontent.com/44264841/210023993-c718fabc-02cf-43ab-8fe9-3722e3c9a785.png)
![image](https://user-images.githubusercontent.com/44264841/210024036-33b7469c-42df-465c-9d9c-040ebd56ef60.png)

**Comment by tryforceful** [comment]
In v3.0 there is now [an option to hide the header](https://vcalendar.io/datepicker/time-picker.html#hide-header), as OP requested

**Comment by tryforceful** [comment]
What I really want, however, is a way to customize this section per locale... the standard formatting doesn't work well in Japanese, for example:

![image](https://user-images.githubusercontent.com/8162501/229751301-abc2861b-e839-4342-a7bd-93f5f658936f.png)

(This belongs in another issue probably but, figured I'd mention it.)

**Comment by jaletechs** [comment]
I can confirm this works in v3.0

**Comment by valentinhttr** [comment]
> What I really want, however, is a way to customize this section per locale... the standard formatting doesn't work well in Japanese, for example:
> 
> ![image](https://user-images.githubusercontent.com/8162501/229751301-abc2861b-e839-4342-a7bd-93f5f658936f.png)
> 
> (This belongs in another issue probably but, figured I'd mention it.)

Hi @tryforceful Do you found a workaround please?

I'd like to display "Arrival time" for the start of the range and "Departure time" for the end.
