### ISSUE TITLE
Docs folder missing after 0.9.0

### ISSUE THREAD

**Issue by EricMcRay** [nathanreyes/v-calendar#128]
Hi @nathanreyes, I think you added docs folder to gitignore at version 0.9.0. Can you add docs to git again? Because I cant run dev script, It gives a error because of docs folder missing. Also, some people may want to do some contribution to docs.

**Comment by nathanreyes** [comment]
The main reason that I removed it is because you graciously added the documentation for your `src` changes, but that documentation site is no longer publicly used. The new docs is now at [docs.vcalendar.io](docs.vcalendar.io) (which I would encourage others to contribute to). Basically, I didn't want to mislead contributors into thinking those docs were still in use.

Still, it seems that you are also using it to test changes to the code using the built-in examples. Is that true?

**Comment by EricMcRay** [comment]
I tried to setup some sandbox env for this project but It was not working properly. So I use docs to test some changes and I was really helpful. 

Maybe, a development environment or some documentation about it would be nice. So people can contribute without hassle and I think using the same env decrease conflicts, bugs, etc.

**Comment by nathanreyes** [comment]
I agree. I would love to be able to use Evan You's new project [Vuepress](https://vuepress.vuejs.org) for both the docs and showing different examples. Not sure if it could properly use plugin components though.

**Comment by nathanreyes** [comment]
Next release will include the new version of the docs site implemented using [Vuepress](https://vuepress.vuejs.org).

This will be really nice because you can contribute to the docs for API changes, examples and detailed explanations using markdown with inline components and hot reloading.

**Comment by nathanreyes** [comment]
Closing outstanding issue.
