### ISSUE TITLE
Discussion for Milestone 1

### ISSUE THREAD

**Issue by nathanreyes** [nathanreyes/v-calendar#167]
Hello Everyone,

Just wanted to thank everyone for their feedback, with special thanks to @EricMcRay for his help with some of the issues. I wanted to give a little direction for where things are and your feedback on some upcoming features.

* Docs Site Changes (80% Complete): The changes are almost complete for the new docs site using [Vuepress](https://vuepress.vuejs.org). This should allow for more more complete and interactive examples, as well as provide an easier way for people to make contributions to the docs and examples of their own.

* Year Calendar View (80% Complete): This is been a big request when collaborating with others. This will support displaying any number of calendar panes using props for `rows` and `columns`. This will deprecate `is-double-paned`.

* Input Debounce for Date Picker Input (100% Complete)

* CSS Grid for calendar pane and day layout (100% Complete). I think CSS grid support has reached a point that it can be used for this forward-looking plugin. It has [limited support](https://caniuse.com/#feat=css-grid) for IE11, but I believe the payoff in performance and flexibility for future features will be worth it.

* Styling Flexibility: Looking back, I probably would not have focused so much on inline styles, but I would like to still support it. For this next release, I would like to better document how to apply your own css styles by wrapping the component and applying `/deep/` selectors to your css. I don't foresee problems with this approach, but if anyone has any experience or success with this approach, please let me know.

* Locale Flexibility (5% Complete): Right now locale settings are set globally. This is mainly designed for performance reasons (global day data for use in all calendar). Not sure how this will go, but would like feedback on this none-the-less.

* Bug Fixes: Because there's always bugs! I'll try and tag the ones that seem most critical for this next release.

Cheers!

**Comment by kl3sk** [comment]
I propose to make a template for issues, at least with an example (jsfiddle or something else) of the problem found.

**Comment by bg** [comment]
Could you please indicate where making IE11 work again sits with your priorities.

You've hinted above you know the choice of CSS grid support would come at the expense of only partial support for IE11. Could that choice be playing into our current troubles, or is it unrelated?

_Note: We're early in the evaluation of v-calendar, which, aside from no IE11 support, is otherwise the leading choice. We have a 2nd choice with stronger cross-browser support in view in case it doesn't pan out, but we don't like it as much as v-calendar, so I'm hoping the remaining issues with supporting IE11 can be resolved with a reasonable amount of effort. I understand others say an older version works with IE11, but staying stuck on an older version nobody is updating is an unattractive alternative._

**Comment by nathanreyes** [comment]
Closing outstanding issue.
