### ISSUE TITLE
[Bug] v-model not working (can't deselect initial v-model)

### ISSUE THREAD

**Issue by JCKodel** [nathanreyes/v-calendar#172]
This app allow the user to select 12 dates on a date picker (each time user clicks a date, available-dates are recalculate to disallow selecting dates < 48 hours between). Everything worked fine.

Now, I need to allow the user to auto select the dates (for the lazy users who don't want to click 12 times). I'm doing this setting the array bound to v-model with 12 dates.

The bug: the date picker show the 12 dates correctly (as shown in fiddle below), but, internally, it appears it have no date selected!  I can't unselect dates, because when I click one selected date, date-picker will add a 13th date to my calendar (it ignores the 12 on v-model and try to add a new one). Clicking it again, my v-model array gets back to 12 dates.

Fiddle: https://jsfiddle.net/wsudqjk6/ (it will pre-select 12 dates and you will not be able to desselect those)

**Comment by kl3sk** [comment]
I don't know if this is considered as a bug or if @nathanreyes  do this on his own.

I've update your [fiddle](https://jsfiddle.net/klesk/petrmo1f/) with a working version.
Because i don't know luxon i've made it with regular Date object. 
But as you can see on the fiddle, if ``bugged ?`` checked I have the same problem.

What I've understand is on the date object it self. If you set Hours, Minutes, Second and Milliseconds to Zero. Everything is working again.

Is it a bug ? I let @nathanreyes decide on it.

**Comment by dchinu97** [comment]
Any updates on this? Still facing the same issue, cannot deselect dates

**Comment by nathanreyes** [comment]
Closing outstanding issue. Please generate new issue if needed.

Please reference [this example](https://vcalendar.io/examples/datepickers.html#legacy-multiple-mode) for guidance on 
implementing multiple date select in 2.0.
