### ISSUE TITLE
Option popover-keep-visible-on-input doesn't work

### ISSUE THREAD

**Issue by romangit** [nathanreyes/v-calendar#192]
From v-calendar@0.9.3 option popover-keep-visible-on-input doesn't work. 

[v-calendar@0.9.7 - Nonworking](https://jsfiddle.net/7scdxn9w/2/)
[v-calendar@0.9.2 - Working](https://jsfiddle.net/7scdxn9w/3/)

**Comment by M165437** [comment]
The problem lies in the `value` function inside `src/components/DatePicker.vue`:

In 0.9.2 there was the [line 290](https://github.com/nathanreyes/v-calendar/blob/v0.9.2/src/components/DatePicker.vue#L290) that prevented the popover from hiding. It's gone since 0.9.3:

```javascript
if (this.popoverKeepVisibleOnInput) return;
```

I propose the following change to fix the bug:

```javascript
value() {
  this.assignPageRange();
  if (!this.disableFormatInput) this.formatInput();
  if (
    this.mode !== 'multiple'
    && !this.disablePopoverForceHidden
    && !this.popoverKeepVisibleOnInput
  ) {
    this.hidePopover();
  }
  this.disableFormatInput = false;
  this.disablePopoverForceHidden = false;
}
```

@nathanreyes Do you want me to create a pull request or will you fix this yourself? By the way, thank you! Great plugin!

**Comment by M165437** [comment]
@nathanreyes I went ahead and submitted the pull request … you decide :-)

**Comment by arthuraulin** [comment]
Hi! I had the same issue on current 1.0.1 version so I opened a new pull request as the code structure seem to have changed a bit since then
