### ISSUE TITLE
locale dont work

### ISSUE THREAD

**Issue by talifa** [nathanreyes/v-calendar#261]
Hi!
I use this cdn installation https://docs.vcalendar.io/#installation and everything work okay, but completely ignore "locale" string. Why?

`<v-date-picker :mode="mode" is-inline v-model="selectedDate" :pane-width="290"  :theme-styles="themeStyles"> </v-date-picker>`

and 

```
new Vue({
              el: '.sib-wide-box',
              data: {
                mode: 'single',
                locale: 'en',
                selectedDate: new Date(),
                 },
            });
```

**Comment by Alexpri** [comment]
Hello, it doesn't work because this plugin doesn't have such local. Try to go to the file "v-calendar/src/utils/locales.js" where you can find any local that you need. I spent some time with formatting issue and found this file. { locale: 'ca' } works for me. In few words they have "en-GB" or "en-US"

**Comment by talifa** [comment]
@Alexpri thanks!! but i dont really understand how can i use this with cdn..

**Comment by Alexpri** [comment]
For me it works in the following way
in the file main.js

import Vue from 'vue'
import VCalendar from 'v-calendar'

Vue.use(VCalendar, {
  locale: 'en-GB'
})
