### ISSUE TITLE
Custom popover in date picker

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#46]
Is it possible to build a custom popover for an inline date picker?

**Comment by nathanreyes** [comment]
Actually, you can, but you have to use either the `label` method or the `component` method. You can't use the `slot` method because date pickers don't currently pass down nested slots.

I created a [fiddle](https://jsfiddle.net/nathanreyes/xnxpafbs/) that you can reference. It shows using the `label` method as well as the `component` method. I have to use the awkward `Vue.component` method of creating a custom component, but in a Node environment you would just import your custom Vue single file component.

I plan on documenting this better, but hopefully this helps.

**Comment by luiztsmelo** [comment]
Thanks @nathanreyes. I was able to build it using the single file component, but now it's the hardest part. Let me explain what I'm trying to do: 

I'm building this date picker for a booking app. I want to show the price for each day (in holidays the price is higher) in the popover, and when the user selects a range of days, the popover would sum the prices automatically.

How could I pass the day selected info to popover component? PS: It's a list of houses and sailings.

**Comment by nathanreyes** [comment]
Oh ok cool. What I would do is get the `attribute.targetDate`. You can use the `startDate` and `endDate` to then loop through each day and calculate the total price. Your SFC then would need to have access to this info either using Vuex or importing some data objects/functions into it.

Does that make sense?

**Comment by luiztsmelo** [comment]
I didn't figure out how to get this `attribute`. When we select a day in date picker, what happens?

**Comment by nathanreyes** [comment]
If you declare a prop named `attribute` on your single file component, it will get passed in by `v-date-picker`.

**Comment by luiztsmelo** [comment]
Oh, nice. I saw a variable called `daySpan`. It works like a charm. I just had to add 1 to it. Thanks for help @nathanreyes.
