### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by soullpoint** [nathanreyes/v-calendar#633]
Hi, just wondering if you are planning to add support for Vue 3?

I don't seem to be able to use it in a new project I'm starting.

I'm getting an error "n.a.mixin is not a function" or something to that effect. If it's something I might be doing, please let me know!

Thanks for your work!

**Comment by kylegosen** [comment]
Wondering the same thing.

**Comment by jlewin** [comment]
I'm also hitting this same error in the browser when using vite and yarn

**Comment by mits87** [comment]
Now the Vue3 was released so I'm looking forward to see an update of v-calendar.

**Comment by swifthing** [comment]
Same question here,

**Comment by rodrigomata** [comment]
Same here, tried the @next branch and same stuff

**Comment by pgolemanov** [comment]
Hi Nathan, could you please share with us  if are planning to support Vue3. Thanks

**Comment by dominykasgithub** [comment]
would be great to have vue3

**Comment by nataliawww** [comment]
+1

**Comment by santicros** [comment]
+1 Hoping that will have support :)

**Comment by solak647** [comment]
+1 Would be great

**Comment by victor-gabou** [comment]
+1

**Comment by TWithers** [comment]
+1

**Comment by securedeveloper** [comment]
+1

**Comment by abunuwas** [comment]
This needs fixing or this library will probably be dead soon, which is a pity

**Comment by nathanreyes** [comment]
Rest assured this is high on the priority list.

I don't know how to do plugins in Vue 3 yet, but I am going to try and learn this weekend and hopefully implement in a way that will integrate nicely with Vue 2, if possible.

**Comment by nathanreyes** [comment]
It doesn't look like supporting Vue 2 and 3 will be possible, or preferred at the least. My thinking is to start work on a Vue 3 compatible version on the `next` branch and publish a `3.0.0-alpha.0` as soon as possible. I have also wanted to convert this library to using Rollup as it will properly generate esm builds that is more easily consumed by applications. I'm sure that will be quite an intrusive endeavor, but hopefully not as difficult as it seems.

If anyone has any other recommendations or experience, please advise. Also, peep the `next` branch and issue a PR if you are willing to get in on the action 😄 

Happy coding.

**Comment by moutz** [comment]
Hello, I wanted to watch if I can do something for helping in vue3 support. I pull the next branch but it looks like I can't build anything because of the vuepress dependency. 

Also, what is the best way to dev/watch code in action using this repo ?

Thank you for your work, and this very usefull plugin.

**Comment by jlewin** [comment]
@nathanreyes - exciting to hear, thanks for the update. 

Like @moutz I'd be interested in helping if I could sort out my roadblocks - any chance there's a dev discussion group or chat system where interested parties hang out?

**Comment by nathanreyes** [comment]
I'm doing experimental work on a [separate repo](https://github.com/nathanreyes/vue3-component-library) just to get things working. It is a fork of another repo that had some things configured out of the box, like Rollup + PostCSS + Vue 3. Rollup Plugin Vue I think still has some bugs with using PostCSS in the style blocks.

I'm still debating creating a new repo since this is architecturally a whole new project. However, the issues and commit history would get lost out if I did that.  🤔 

I have the most things working locally (sans DatePicker component) using a Rollup config with ES builds and Vue 3...I just haven't pushed the changes yet. Converting to Vue 3 was interesting. Most of the work was syntax changes with render functions (still not sure I'm crazy about using event handlers like `onDayclick`, it just looks kind of ugly to me).

Here is an invite link to a discord server that I started a while ago but haven't shared with anyone yet. Anyone is free to join in. https://discord.gg/y4UmWeJp

**Comment by michaelhays** [comment]
Hey @nathanreyes, I'm getting an "Invite Invalid" on that Discord link.

**Comment by nathanreyes** [comment]
Oh. Here's a permanent link you can use. https://discord.gg/QrsUn4seXM

**Comment by nathanreyes** [comment]
Please reference the [README](https://github.com/nathanreyes/v-calendar/blob/next/README.md) on the next branch for testing Vue 3 compatibility issues. It uses Rollup so if you import in a module-bundler environment it should use the module build. UMD and CommonJS are also included but are not documented nor I haven't tested them much. It has Typescript support built in, but the types still need to be fleshed out. Just wanted to get it working for now.

Install using the `next` tag (`v-calendar@next`).

I'd recommend reporting any quirks or bugs to the Discord channel for now in the `vue3` channel since things are still fluid at the moment.

**Comment by ryoha000** [comment]
I think there is a lack of type definitions for vue3. (Example: `DatePicker`)

**Comment by nathanreyes** [comment]
That is correct. They are still in work. Going to close this issue and recommend new requests be submitted as new issues.

**Comment by ntdatstudy** [comment]
hi @nathanreyes, I wanna override the content/events on weekdays by day-content slot template but it didn't work. How can I resolve it? Can you help me please? Thank you.
