### ISSUE TITLE
Can you keep date range UI like V1.0.8??

### ISSUE THREAD

**Issue by hargreaveshklimit** [nathanreyes/v-calendar#675]
I think the version 1.0.8 date range is good enough. For now v1.1.1 the date range UI is not convenient in vuetify.

**Comment by nathanreyes** [comment]
Are you referring to having the single `input` element for the range input?

**Comment by nathanreyes** [comment]
The changes were introduced in 2.0 so that developers have the ultimate flexibility for how they want to present date ranges as separate inputs. Basically, you need to provide your own inputs now (for single dates and date ranges alike). While the old UI was probably convenient for some occasions, it was still limiting for many others.

There is a lot of work still left to be done on this plugin so I can't really justify refactoring everything to go back to the pre-v2 user interface. That would require a lot of work with the parsing/formatting logic. I'd recommend sticking with `1.0.8` if this is unacceptable for you.

**Comment by hargreaveshklimit** [comment]
> The changes were introduced in 2.0 so that developers have the ultimate flexibility for how they want to present date ranges as separate inputs. Basically, you need to provide your own inputs now (for single dates and date ranges alike). While the old UI was probably convenient for some occasions, it was still limiting for many others.
> 
> There is a lot of work still left to be done on this plugin so I can't really justify refactoring everything to go back to the pre-v2 user interface. That would require a lot of work with the parsing/formatting logic. I'd recommend sticking with `1.0.8` if this is unacceptable for you.

Okay, i will keep `1.0.8` version. Great Thanks

**Comment by andreasvirkus** [comment]
@hargreaveshklimit a single input seems to work fine with the `is-range` prop

```
<v-date-picker v-slot="{ inputValue, inputEvents }" v-model="selectedDate" is-range color="indigo">
  <input
    class="input is-small"
    type="text"
    :value="`${inputValue.start} - ${inputValue.end}`"
    v-on="inputEvents.start"
  />
</v-date-picker>


// ...
  data() {
    return {
      selectedDate: {
        start: new Dayjs().subtract(1, 'month').toDate(),
        end: new Dayjs().toDate(),
      },
```
