### ISSUE TITLE
non-passive event listener violation in Chrome

### ISSUE THREAD

**Issue by appml** [nathanreyes/v-calendar#687]
Hi, I start getting this error in Chrome after upgrading to version 86.0.4240.111 (Official Build) (32-bit):

**[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952**

Also losing the hover to focus behavior, used to hover for calendar to popup, now the calendar would show no matter what:

![image](https://user-images.githubusercontent.com/7504229/97637475-1c824e00-1a11-11eb-9426-cda6c0999868.png)

**v-calendar version**: 2.0.1  

Thanks.

**Comment by nathanreyes** [comment]
I will add the passive argument for the touch handlers.

> Also losing the hover to focus behavior, used to hover for calendar to popup, now the calendar would show no matter what:

Not sure I understand what you mean here. One thing that changed in 2.0 is that you need to provide a custom slot for the popover to appear. Otherwise, it will always show inline. Is that what you are asking about?
[Changelog](https://vcalendar.io/changelog/v2.0.html#_7-remove-is-inline-prop)

**Comment by appml** [comment]
@nathanreyes  Custom slot is what I meant.  Thanks for looking into passive argument issue.
