### ISSUE TITLE
Weird max-date prop behavour? Jsfiddle example

### ISSUE THREAD

**Issue by LG0012** [nathanreyes/v-calendar#721]
Hi all, just wondering, is this is how max-date should behave in calendar?

https://jsfiddle.net/Lxsf1mag/

currentDate: new Date(), (2020-11-24 etc.)

:max-date="currentDate"

And you are still able to select 25th day even it's looks like it's disabled?

**Comment by nathanreyes** [comment]
One weird issue here. The max date you provided is in the middle of the day. So technically, part of the day is enabled (before max date), while the other disabled (after max date). 

When the date on the max date is selected, it is using the min time `00:00:00`, so technically it is a valid selection since it always be before the time of `new Date()`.

One solution is to do what the PR currently does and normalize the max date to the last second of the day `23:59:59` and the `min-date` to `00:00:00` (which it already does which is why the `min-date` isn't an issue here).

However, some might want to disable times within a given day as well, like in #723.

So...I'm not sure what the best solution is here. Maybe do the normalization only if `mode: 'date'` has been seen. Otherwise, if any time mode is active (`dateTime` or `time`), then don't normalize the date? And if so , should there be some kind of visual indicator that prevent confusion as you had in this case?

Just thinking out loud here before I merge this PR.
