### ISSUE TITLE
is24hr issue when selecting time

### ISSUE THREAD

**Issue by nik736** [nathanreyes/v-calendar#781]
Hello,

Thanks for your work on this library, I really appreciate it.

I am not sure if this is intended but when having the same date and selecting the first time in 24hr time mode it jumps to the second time. This only happens if the same date is selected, so I am imaging this is probably a bug as our users are very confused by this.

A video that shows the issue: https://jumpshare.com/v/0lVmjHb6FPJEjcjDQpMm

`<v-date-picker v-model="xxx" :min-date="new Date()" :minute-increment="60" mode="dateTime" timezone="utc" locale="de" is24hr is-range></v-date-picker>`

Thanks :)

**Comment by DonnyMarsden** [comment]
Have you found a fix for this?

**Comment by nik736** [comment]
Sadly not, I decided to not go with the 24hr option and only use v-calendar for dates.

**Comment by nathanreyes** [comment]
The time is jumping because the first date becomes a later date than the second one the moment they select a time. 

The picker automatically sorts the dates after the date range value updates as a feature. If the span were longer than a day, this is not an issue because time is a non-factor at that point.

I could see how the natural progression of selecting the first time after a 1 day range selection would be common, so I'll try and see if there is a good solution to this problem. Perhaps any time the first time is set to a later date than the second, then force the second to be equal to the first. Of course, that would only happen if the day span was 1.

**Comment by DonnyMarsden** [comment]
> I could see how the natural progression of selecting the first time after a 1 day range selection would be common, so I'll try and see if there is a good solution to this problem. Perhaps any time the first time is set to a later date than the second, then force the second to be equal to the first. Of course, that would only happen if the day span was 1.

I think that this is the best behaviour for this scenario. It's intuitive that if you move the first date/time past the second, then the second should match the first. (And vice versa because you can move the later time to a time earlier than the start which causes the same swapping behaviour). For now I'm getting past this by using a date-range component that only handles dates and two time components beneath it that handle the times in isolation.
