### ISSUE TITLE
DateTime Picker shows abnormal behavior in case of a timezone

### ISSUE THREAD

**Issue by Rajs0ni** [nathanreyes/v-calendar#796]
DateTime picker is showing miss behavior  when we bind a timezone (CET +1:00 CET from MomentTz.js). It shows two dates selected.

![image](https://user-images.githubusercontent.com/23555742/108958332-d6748880-7698-11eb-88b3-fe92ae08ec29.png)

**Comment by adriaan** [comment]
I'm seeing the same thing

**Comment by p3yman** [comment]
Same problem here. Can we expect a fix on this soon?

**Comment by gonzalo-bl** [comment]
I'm being affected by this issue as well. What is the reason to only support a limited list of timezone names? 
I'd be happy to help with a fix unless there's a good reason not to support all the list of timezones

**Comment by marievidal360** [comment]
Hi @nathanreyes,
This bug comes from a bug in the lib **date-fns-tz** which has been fixed in version 1.1.5.
There was a regexp for IANA timezone which doesn't match some timezones, like `Cuba` or `EST`...
cf. https://github.com/marnusw/date-fns-tz/blob/master/CHANGELOG.md for more details

The minified version of v-calendar (shipped with npm in `lib/v-calendar.umd.min.js`) contains the bogus version of **date-fns-tz**.

Could you upgrade this dependency in the next version? :pray:

**Comment by filoromz** [comment]
for those experiencing this issue, I made a PR here which bumps the offending package `date-fns-tz`
https://github.com/nathanreyes/v-calendar/pull/1213

in the meantime, to unblock anyone that needs this fix, I published a separate package that contains the updated `date-fns-tz` package: https://www.npmjs.com/package/@rommel.vergara/v-calendar

alternatively, you can git clone v-calendar and bump `date-fns-tz` yourself in the package.json and recompile the components, then copy the files over to your project that consumes it.

thanks!
