### ISSUE TITLE
InputValue is not updated reactively in range date picker.

### ISSUE THREAD

**Issue by manduMY** [nathanreyes/v-calendar#818]
When selecting a date in the range date picker, the end date does not change in real time if it is earlier than the start date. 

When the start date and end date are clicked, they are changed normally, but the moment the mouse pointer is placed on the end date after clicking the start date, they are not updated in real time.

Does anyone know the solution?

i want to:
![2021-03-14 164454](https://user-images.githubusercontent.com/45209114/111061181-601fb500-84e5-11eb-8cc6-8bc68c0d131c.png)

current: https://vcalendar.io/
![2021-03-14 164722](https://user-images.githubusercontent.com/45209114/111061198-6dd53a80-84e5-11eb-842b-d8550b23156f.png)

Even if the same function is coded identically on the official website, the result does not change.

If the end date is later than the start date, it works normally.
![2021-03-14 165603](https://user-images.githubusercontent.com/45209114/111061370-5c406280-84e6-11eb-9940-b0b58bfd4ebc.png)

**Comment by nathanreyes** [comment]
> When selecting a date in the range date picker, the end date does not change in real time if it is earlier than the start date.

In this instance, the first input will update because it is treated as the start date. This is implemented in a recent release because it could be confusing to the user if the second input was an earlier date than the first input.

> When the start date and end date are clicked, they are changed normally, but the moment the mouse pointer is placed on the end date after clicking the start date, they are not updated in real time.

While the user is dragging to select the 2nd date, the `input` event is not emitted. The bound value won't change. If you'd like to know what range is being dragged by the user, please use the `drag` event.

I may have misunderstood your question. Is that where you were asking?

**Comment by manduMY** [comment]
Hello nathanreyes,
Yes, you are right. If the end date is earlier than the start date, the start input tag and end input tag are not changed.
These things have changed in the latest release.
I should use it as it is.
Thanks for the answer ~!
