### ISSUE TITLE
Cannot Pass Dynamic Value to :disabled-dates props @next version

### ISSUE THREAD

**Issue by newlifehaonan** [nathanreyes/v-calendar#837]
passing dynamic value to :disabled-dates when date picker is in range mode and min/max-dates is set, picker cannot select the end date. the use case scenario is set a range of disabled date base on the selected start date.

see this demo https://codesandbox.io/s/restless-smoke-2vmun?file=/src/App.vue for reference.

**Comment by nathanreyes** [comment]
I think this modified example should help.
https://codesandbox.io/s/unruffled-davinci-wiovb?file=/src/App.vue

The first disabled date was always intersecting the drag value because it _included_ the range start date. This would always invalidate any dragged range from that point on. 

This disabled date just needs to subtract one day.
```
{ start: null, end: new Date(range.start.getFullYear(), range.start.getMonth(), range.start.getDate() - 1 }
```
The example also refactors to only set the disabled dates when dragging starts (old drag value is null) and clears the disabled dates when dragging finishes (new date range value is set).

Hope that helps. Since what you are trying to do is quite common (limit number of days selected), I'm working on a way to more simply accomplish this rather than the manual technique currently required.
